/**
 * Bighabesha Shop - Ethiopian Bank Receipt Verification Engine
 * Domain Contracts, Interfaces, Data Transfer Schemas & RFC 7807 Error Models
 *
 * Designed in Phase 1 (ADR-001 / ARCHITECTURE-RECEIPT-VERIFICATION)
 * Implemented for Phase 2: API Architecture & Contracts
 */

// ============================================================================
// 1. Core Enumerations & Literal Unions
// ============================================================================

/** Supported Ethiopian banking and mobile wallet rails */
export type SupportedBank = 'cbe' | 'telebirr' | 'abyssinia' | 'unknown';

/** Channel through which the customer or administrator submitted the receipt */
export type ReceiptInputSource =
  | 'telegram_photo'
  | 'telegram_document'
  | 'webapp_upload'
  | 'sms_forward'
  | 'manual_admin_entry';

/** Allowed MIME types for uploaded receipt artifacts */
export type ReceiptMimeType =
  | 'image/jpeg'
  | 'image/png'
  | 'image/webp'
  | 'application/pdf'
  | 'text/plain';

/** Methodology through which the transaction reference code was decoded */
export type DecodeMethod =
  | 'qr_matrix'
  | 'pdf_stream'
  | 'ocr_regex'
  | 'sms_regex'
  | 'manual_code';

/** Final operational status of the verification pipeline */
export type VerificationStatus =
  | 'auto_verified'
  | 'pending_manual_review'
  | 'rejected'
  | 'upstream_failure';

/** The four discrete security gate pillars evaluated before fulfillment */
export type SecurityPillarId =
  | 'anti_replay'
  | 'beneficiary_whitelist'
  | 'exact_amount'
  | 'recency_window';

/** State of the circuit breaker protecting upstream bank portals */
export type CircuitBreakerState = 'CLOSED' | 'OPEN' | 'HALF_OPEN';

// ============================================================================
// 2. Standardized Error Taxonomy (RFC 7807 Problem Details)
// ============================================================================

/**
 * Standardized Machine-Readable Error Codes
 */
export type VerificationFailureCode =
  | 'RECEIPT_ALREADY_USED'       // 409 Conflict: Transaction reference already matched
  | 'BENEFICIARY_MISMATCH'        // 422 Unprocessable: Transfer was sent to unauthorized account
  | 'AMOUNT_MISMATCH'             // 422 Unprocessable: Amount verified is less than net payable
  | 'RECEIPT_EXPIRED'             // 422 Unprocessable: Timestamp outside acceptable temporal window
  | 'QR_DECODE_FAILED'            // 422 Unprocessable: Image could not be decoded to QR matrix
  | 'BANK_PORTAL_UNAVAILABLE'     // 504 Gateway Timeout: Upstream bank connection timed out / reset
  | 'PORTAL_GEOBLOCKED'           // 502 Bad Gateway: Upstream gateway blocked non-Ethiopian egress
  | 'UNSUPPORTED_BANK'            // 400 Bad Request: Rail or format not supported by automated engine
  | 'CORRUPTED_FILE'              // 400 Bad Request: Magic byte validation or image parsing failed
  | 'RATE_LIMITED'                // 429 Too Many Requests: Rate limit exceeded for verification
  | 'INTERNAL_ENGINE_ERROR';      // 500 Internal Server Error: Unexpected runtime failure

/**
 * RFC 7807 Problem Details Specification Schema
 * @see https://datatracker.ietf.org/doc/html/rfc7807
 */
export interface Rfc7807ProblemDetails {
  /** URI identifier that categorizes the problem type */
  type: string;
  /** Short, human-readable summary of the problem type */
  title: string;
  /** The HTTP status code generated by the origin server */
  status: number;
  /** Human-readable explanation specific to this occurrence of the problem */
  detail: string;
  /** Relative URI reference identifying the specific occurrence */
  instance: string;
  /** Application-specific standardized error code */
  code: VerificationFailureCode;
  /** Structured diagnostic context regarding the failure */
  details?: Record<string, unknown>;
  /** Concrete guidance to help the client or operator resolve the condition */
  remediation_hint: string;
  /** Timestamp when the failure occurred in ISO 8601 format */
  timestamp: string;
}

/**
 * Base domain exception for receipt verification errors conforming to RFC 7807.
 */
export class ReceiptVerificationError extends Error {
  public readonly problemDetails: Rfc7807ProblemDetails;

  constructor(
    code: VerificationFailureCode,
    status: number,
    title: string,
    detail: string,
    remediation_hint: string,
    instance: string = '/api/receipts/verify',
    details?: Record<string, unknown>
  ) {
    super(detail);
    this.name = 'ReceiptVerificationError';
    this.problemDetails = {
      type: `https://bighabesha.shop/errors/${code.toLowerCase().replace(/_/g, '-')}`,
      title,
      status,
      detail,
      instance,
      code,
      details,
      remediation_hint,
      timestamp: new Date().toISOString(),
    };
  }
}

export class ReceiptAlreadyUsedError extends ReceiptVerificationError {
  constructor(reference: string, existingOrderId?: string, instance?: string) {
    super(
      'RECEIPT_ALREADY_USED',
      409,
      'Receipt Already Used',
      `Transaction reference '${reference}' has already been verified and credited to another order.`,
      'This transfer receipt has already been used. Please submit the receipt for your current payment or contact support.',
      instance,
      { reference, existingOrderId }
    );
    this.name = 'ReceiptAlreadyUsedError';
  }
}

export class BeneficiaryMismatchError extends ReceiptVerificationError {
  constructor(bank: SupportedBank, actualBeneficiary: string, expectedAccounts: string[], instance?: string) {
    super(
      'BENEFICIARY_MISMATCH',
      422,
      'Beneficiary Account Mismatch',
      `Payment was made to '${actualBeneficiary}', which does not match official shop accounts.`,
      'The transfer was sent to an unauthorized recipient. Payments must be sent strictly to Bighabesha Shop official accounts.',
      instance,
      { bank, actualBeneficiary, expectedAccounts }
    );
    this.name = 'BeneficiaryMismatchError';
  }
}

export class AmountMismatchError extends ReceiptVerificationError {
  constructor(expectedAmountEtb: number, actualAmountEtb: number, instance?: string) {
    super(
      'AMOUNT_MISMATCH',
      422,
      'Payment Amount Mismatch',
      `Verified bank payment of ${actualAmountEtb} ETB is less than required order total of ${expectedAmountEtb} ETB.`,
      `The transferred amount (${actualAmountEtb} ETB) is less than the required order total (${expectedAmountEtb} ETB). Please transfer the remaining balance.`,
      instance,
      { expectedAmountEtb, actualAmountEtb, differenceEtb: expectedAmountEtb - actualAmountEtb }
    );
    this.name = 'AmountMismatchError';
  }
}

export class ReceiptExpiredError extends ReceiptVerificationError {
  constructor(orderCreatedAt: Date, txTimestamp: Date, windowMinutes: { before: number; after: number }, instance?: string) {
    super(
      'RECEIPT_EXPIRED',
      422,
      'Receipt Stale or Expired',
      `Transaction timestamp (${txTimestamp.toISOString()}) is outside allowed window around order creation (${orderCreatedAt.toISOString()}).`,
      'The transfer timestamp is outside the valid transaction window. Please complete transfers within 2 hours of checkout.',
      instance,
      { orderCreatedAt: orderCreatedAt.toISOString(), txTimestamp: txTimestamp.toISOString(), windowMinutes }
    );
    this.name = 'ReceiptExpiredError';
  }
}

export class QrDecodeFailedError extends ReceiptVerificationError {
  constructor(reason?: string, instance?: string) {
    super(
      'QR_DECODE_FAILED',
      422,
      'QR Code Matrix Decoding Failed',
      reason || 'Image matrix does not contain a recognizable 2D QR code or the image is too blurry.',
      'Could not read the QR code on the receipt screenshot. Please ensure the image is clear, uncropped, and not blurry, or enter the reference code manually.',
      instance,
      { reason }
    );
    this.name = 'QrDecodeFailedError';
  }
}

export class BankPortalUnavailableError extends ReceiptVerificationError {
  constructor(bank: SupportedBank, reason: string, instance?: string) {
    super(
      'BANK_PORTAL_UNAVAILABLE',
      504,
      'Bank Confirmation Portal Unavailable',
      `Upstream verification portal for ${bank.toUpperCase()} timed out or failed to respond: ${reason}`,
      'The bank confirmation portal is currently unresponsive. Your receipt has been routed to our store administrators for manual review.',
      instance,
      { bank, reason }
    );
    this.name = 'BankPortalUnavailableError';
  }
}

export class PortalGeoblockedError extends ReceiptVerificationError {
  constructor(bank: SupportedBank, proxyHost?: string, instance?: string) {
    super(
      'PORTAL_GEOBLOCKED',
      502,
      'Bank Portal Geoblocked or Proxy Egress Failed',
      `Access to ${bank.toUpperCase()} transaction verification portal was blocked or Ethiopian residential proxy failed.`,
      'Bank gateway routing encountered a regional network block. Receipt routed to administrator review queue for manual verification.',
      instance,
      { bank, proxyHost }
    );
    this.name = 'PortalGeoblockedError';
  }
}

export class UnsupportedBankError extends ReceiptVerificationError {
  constructor(detectedRail: string, instance?: string) {
    super(
      'UNSUPPORTED_BANK',
      400,
      'Unsupported Banking Rail',
      `Automated verification is not currently supported for banking rail: '${detectedRail}'.`,
      'Automated verification currently supports CBE and Telebirr. Other banks will be reviewed manually by administrators.',
      instance,
      { detectedRail }
    );
    this.name = 'UnsupportedBankError';
  }
}

// ============================================================================
// 3. Ingestion & Pre-Processing Models
// ============================================================================

/** Extracted reference data parsed from QR matrix, vector PDF, or raw text */
export interface ExtractedReceiptReference {
  /** The identified bank rail */
  bank: SupportedBank;
  /** Raw unconverted reference string as extracted from receipt */
  rawReference: string;
  /** Normalized canonical reference string (uppercase, stripped whitespace) */
  normalizedReference: string;
  /** Direct bank confirmation URL if decoded from a QR code */
  sourceUrl?: string;
  /** Transfer amount in ETB if embedded directly in QR payload/SMS */
  amountEtb?: number;
  /** Timestamp when extraction occurred */
  extractedAt: Date;
  /** Confidence score between 0.0 and 1.0 */
  confidence: number;
  /** Method through which extraction was performed */
  decodeMethod: DecodeMethod;
  /** Diagnostic snippet of raw unparsed text or payload */
  rawPayloadSnippet?: string;
  /** Optional bounding box of decoded QR matrix in source image */
  qrBoundingBox?: {
    x: number;
    y: number;
    width: number;
    height: number;
  };
}

/** Configurable tuning parameters for image pre-processing and matrix decoding */
export interface IngestionOptions {
  /** Maximum pixel dimension cap to prevent decompression bombs (default: 16777216) */
  maxPixels?: number;
  /** Whether to apply grayscale and dynamic contrast stretching before decoding */
  enableContrastEnhancement?: boolean;
  /** Try multiple binarization thresholds on low-contrast images */
  multiPassThresholding?: boolean;
  /** Maximum execution timeout in milliseconds for ingestion (default: 5000ms) */
  timeoutMs?: number;
}

/** Diagnostic result returned by the QR test endpoint */
export interface QrTestResult {
  /** Whether a QR matrix was successfully located and decoded */
  success: boolean;
  /** Raw decoded text decoded from the matrix */
  rawText?: string;
  /** Structured reference extracted from the raw QR text */
  extractedReference?: ExtractedReceiptReference;
  /** Total processing duration in milliseconds */
  decodeDurationMs: number;
  /** Number of pre-processing threshold passes attempted */
  passesAttempted: number;
  /** Error description if decoding failed */
  error?: string;
}

// ============================================================================
// 4. Bank Adapter & Gateway Models
// ============================================================================

/** Normalized transaction payload confirmed by the bank confirmation portal */
export interface BankTransactionPayload {
  /** The confirmed banking rail */
  bank: SupportedBank;
  /** Official bank transaction reference code */
  transactionReference: string;
  /** Confirmed transferred amount in Ethiopian Birr */
  amountEtb: number;
  /** Transaction service fee if recorded */
  feeEtb?: number;
  /** Currency code (strictly 'ETB') */
  currency: 'ETB';
  /** Sender customer name if exposed by confirmation portal */
  senderName?: string;
  /** Sender phone number or partial account if available */
  senderIdentifier?: string;
  /** Confirmed beneficiary account number or merchant identifier */
  beneficiaryAccount: string;
  /** Confirmed beneficiary account name (e.g. 'Samuel Girma') */
  beneficiaryName: string;
  /** Verified bank transaction execution timestamp */
  transactionTimestamp: Date;
  /** Payment delivery channel (e.g. 'cbe_birr', 'internet_banking', 'telebirr_app') */
  paymentChannel?: string;
  /** Full unstructured diagnostic payload or HTML/PDF attributes for audit */
  rawAuditTrail: Record<string, unknown>;
}

/** Configuration options passed to bank adapter verification queries */
export interface BankVerificationOptions {
  /** Hard network timeout in milliseconds (default: 7500ms) */
  timeoutMs?: number;
  /** Custom egress proxy URL for bypassing geo-blocks (e.g. for Telebirr) */
  proxyUrl?: string;
  /** Force port 100 direct egress for CBE */
  forcePort100?: boolean;
  /** Bypass circuit breaker state (admin override only) */
  bypassCircuitBreaker?: boolean;
}

// ============================================================================
// 5. 4-Pillar Security Gate Models
// ============================================================================

/** Result of evaluating an individual security pillar */
export interface SecurityPillarEvaluation {
  /** The security pillar evaluated */
  pillar: SecurityPillarId;
  /** Whether this individual pillar assertion passed */
  passed: boolean;
  /** Expected value or constraint definition */
  expected: string | number;
  /** Actual value extracted from bank confirmation */
  actual: string | number;
  /** Human-readable explanation or diagnostic log */
  details?: string;
  /** Allowable variance or tolerance (e.g. in ETB or minutes) */
  tolerance?: number;
}

/** Comprehensive result of the 4-Pillar Security Gate */
export interface SecurityGateResult {
  /** True strictly when ALL four pillars have passed */
  passed: boolean;
  /** Ordered list of evaluations for each of the 4 pillars */
  evaluations: SecurityPillarEvaluation[];
  /** The first failing pillar evaluation if any failed */
  failedPillar?: SecurityPillarEvaluation;
  /** Timestamp when evaluation completed */
  evaluatedAt: Date;
}

/** Minimal order context required by the Security Gate */
export interface OrderSecurityContext {
  /** Unique Order ID */
  orderId: string;
  /** Telegram User ID of the buyer */
  userId: number;
  /** Net payable order amount in ETB after discounts */
  netPayableEtb: number;
  /** Payment rail selected by buyer during checkout */
  paymentRail: SupportedBank;
  /** Order creation timestamp */
  orderCreatedAt: Date;
}

/** Store configuration mapping bank rails to approved beneficiary accounts */
export interface BeneficiaryWhitelistConfig {
  cbe: string[];
  telebirr: string[];
  abyssinia?: string[];
}

/** Temporal recency window configuration */
export interface RecencyWindowConfig {
  /** Maximum minutes prior to order creation that slip timestamp is accepted */
  minutesBefore: number;
  /** Maximum minutes after order creation that slip timestamp is accepted */
  minutesAfter: number;
}

// ============================================================================
// 6. Verification Pipeline & Orchestration Models
// ============================================================================

/** Encapsulates an incoming receipt submission request */
export interface ReceiptSubmission {
  /** Target order ID being verified */
  orderId: string;
  /** Buyer Telegram user ID */
  userId: number;
  /** Origin of the submission */
  source: ReceiptInputSource;
  /** Optional binary buffer of image or PDF */
  fileBuffer?: Buffer;
  /** MIME type of fileBuffer if provided */
  mimeType?: ReceiptMimeType;
  /** Optional direct text or reference code if submitted directly */
  directReference?: string;
  /** Optional user note or SMS caption */
  note?: string;
  /** Client IP address for rate limiting and audit */
  ipAddress?: string;
}

/** Complete pipeline outcome produced by the verification orchestrator */
export interface VerificationResult {
  /** True when order is fully verified and eligible for automated fulfillment */
  success: boolean;
  /** Pipeline resolution status */
  status: VerificationStatus;
  /** Target order ID */
  orderId: string;
  /** Confirmed banking rail */
  bank?: SupportedBank;
  /** Confirmed transaction reference */
  transactionReference?: string;
  /** Data extracted during ingestion */
  extractedData?: ExtractedReceiptReference;
  /** Confirmed transaction data from bank portal */
  bankPayload?: BankTransactionPayload;
  /** Detailed 4-pillar gate evaluation */
  securityGateResult?: SecurityGateResult;
  /** Standardized RFC 7807 problem details if verification failed */
  error?: Rfc7807ProblemDetails;
  /** Flag indicating if order was routed to human admin review queue */
  needsAdminReview: boolean;
  /** Reason description provided to admin */
  adminReviewReason?: string;
  /** Verification completion timestamp */
  verifiedAt: Date;
  /** End-to-end execution latency in milliseconds */
  processingDurationMs: number;
}

/** Persisted audit record in SQLite receipt_evidence table */
export interface VerificationAuditRecord {
  /** Internal database auto-increment ID */
  id?: number;
  /** Order ID associated with this verification */
  orderId: string;
  /** Telegram User ID of the buyer */
  userId: number;
  /** Submission channel */
  source: ReceiptInputSource;
  /** Banking rail */
  bank: SupportedBank;
  /** Raw reference as submitted */
  rawReference?: string;
  /** Normalized reference used for anti-replay index */
  normalizedReference?: string;
  /** Order amount in ETB */
  amountEtb?: number;
  /** Confirmed paid amount in ETB from bank */
  verifiedAmountEtb?: number;
  /** Verified beneficiary account number */
  beneficiaryAccount?: string;
  /** Whether all 4 pillars passed */
  securityGatePassed: boolean;
  /** Serialized JSON of SecurityPillarEvaluation[] */
  securityGateEvaluations?: SecurityPillarEvaluation[];
  /** Pipeline resolution status */
  status: VerificationStatus;
  /** Error code if verification failed */
  errorCode?: VerificationFailureCode;
  /** Serialized JSON of raw bank payload */
  rawBankPayload?: Record<string, unknown>;
  /** Client IP address */
  ipAddress?: string;
  /** Creation timestamp */
  createdAt: Date;
  /** Update timestamp */
  updatedAt: Date;
}

/** Query filter for the admin evidence retrieval endpoint */
export interface EvidenceQueryFilter {
  orderId?: string;
  userId?: number;
  bank?: SupportedBank;
  status?: VerificationStatus;
  reference?: string;
  startDate?: string;
  endDate?: string;
  page?: number;
  limit?: number;
}

/** Paginated envelope returned by admin queries */
export interface PaginatedResult<T> {
  items: T[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

// ============================================================================
// 7. Core Service Interfaces (Contracts)
// ============================================================================

/**
 * Service responsible for ingesting files/text, image preprocessing,
 * QR matrix decoding via ZXing, and PDF vector stream extraction.
 */
export interface IReceiptIngestionService {
  /**
   * Ingests a raw file buffer (image or PDF) and extracts reference data.
   * Enforces 16MP caps, decompression bomb protection, and multi-pass decoding.
   */
  ingestBuffer(
    buffer: Buffer,
    mimeType: ReceiptMimeType,
    options?: IngestionOptions
  ): Promise<ExtractedReceiptReference>;

  /**
   * Ingests raw SMS or text message and parses bank transaction references via regex.
   */
  ingestText(rawText: string): Promise<ExtractedReceiptReference>;

  /**
   * Dedicated testing harness for QR decoding on uploaded images.
   */
  testQrMatrix(imageBuffer: Buffer): Promise<QrTestResult>;
}

/**
 * Bank Adapter interface. Implemented by CbeBankAdapter and TelebirrAdapter.
 */
export interface IBankReceiptVerifier {
  /** The specific banking rail handled by this adapter */
  readonly bankRail: SupportedBank;

  /** Checks whether this adapter can verify the given extracted reference/URL */
  canHandle(reference: ExtractedReceiptReference): boolean;

  /**
   * Queries upstream bank portal (e.g. CBE Port 100 or Telebirr proxy)
   * and parses confirmation details. Bound to 7.5s abort timeout.
   */
  verify(
    reference: ExtractedReceiptReference,
    options?: BankVerificationOptions
  ): Promise<BankTransactionPayload>;
}

/**
 * Security Gate verifying the 4 critical pillars before order fulfillment.
 */
export interface ISecurityGate {
  /**
   * Evaluates all 4 pillars atomically.
   */
  evaluate(
    order: OrderSecurityContext,
    bankPayload: BankTransactionPayload
  ): Promise<SecurityGateResult>;

  /**
   * Pillar 1: Anti-Replay check against SQLite receipt_evidence unique index.
   */
  assertAntiReplay(
    normalizedReference: string,
    orderId: string
  ): Promise<{ passed: boolean; existingOrderId?: string }>;

  /**
   * Pillar 2: Beneficiary Whitelist check against configured store accounts.
   */
  assertBeneficiary(
    bank: SupportedBank,
    beneficiaryAccount: string
  ): boolean;

  /**
   * Pillar 3: Amount check ensuring verified payment matches or exceeds net order price.
   */
  assertAmount(
    orderAmountEtb: number,
    paidAmountEtb: number,
    toleranceEtb?: number
  ): boolean;

  /**
   * Pillar 4: Recency Window assertion ensuring payment occurred within allowable timeframe.
   */
  assertRecency(
    orderCreatedAt: Date,
    txTimestamp: Date,
    windowMinutes?: RecencyWindowConfig
  ): boolean;
}

/**
 * Central Orchestrator coordinating Ingestion -> Adapter -> Security Gate -> Resolution.
 */
export interface IReceiptOrchestrator {
  /**
   * Ingests, verifies, evaluates security gate, updates order, and fulfills or routes to fallback.
   */
  processSubmission(submission: ReceiptSubmission): Promise<VerificationResult>;

  /**
   * Triggers manual re-verification of an existing order by an administrator.
   */
  reverifyOrder(orderId: string, adminId: number): Promise<VerificationResult>;

  /**
   * Queries the latest audit evidence record for an order.
   */
  getAuditRecord(orderId: string): Promise<VerificationAuditRecord | null>;

  /**
   * Returns a paginated list of verification audit records with filtering.
   */
  queryEvidence(filter: EvidenceQueryFilter): Promise<PaginatedResult<VerificationAuditRecord>>;
}

// ============================================================================
// 8. Telegram Protocol & Callback Payloads
// ============================================================================

/** Active session payload stored in user session when awaiting receipt */
export interface TelegramReceiptSessionData {
  orderId: string;
  rail: SupportedBank;
  expectedAmountEtb: number;
  startedAt: number;
}

/** Admin inline keyboard action types for receipt verification */
export type TelegramAdminReceiptAction =
  | 'admin_approve'
  | 'admin_reject'
  | 'admin_reverify'
  | 'admin_view_evidence';

/** Structured payload sent in admin alert messages on fallback */
export interface AdminReceiptAlertPayload {
  orderId: string;
  buyerUserId: number;
  buyerUsername?: string;
  productName: string;
  orderAmountEtb: number;
  bankRail: SupportedBank;
  transactionReference?: string;
  securityGateResult?: SecurityGateResult;
  failureCode?: VerificationFailureCode;
  remediationHint?: string;
  hasStoredImage: boolean;
}
