packages:
  - 'bot'
  - 'webapp'

allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
  '@resvg/resvg-js': true

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - sharp
  - '@resvg/resvg-js'
